version: '3.7'
services:
  postgresql:
    image: debezium/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - net

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@localhost.de"
      PGADMIN_DEFAULT_PASSWORD: "admin123"
    networks:
      - net

  connect:
    image: debezium/connect
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: "broker:9092"
      GROUP_ID: "1"
      CONNECT_TOPIC_CREATION_ENABLE: "true"
      CONFIG_STORAGE_TOPIC: "qna.configs"
      OFFSET_STORAGE_TOPIC: "qna.offset"
      STATUS_STORAGE_TOPIC: "qna.status"
    networks:
      - net
      
  smtp4dev:
    image: rnwood/smtp4dev
    ports:
      - "3000:80"
      - "25:25"
    networks:
      - net

volumes:
  postgresql_data:
    driver: local
  pgadmin_data:
    driver: local
    
networks:
  net:
    driver: bridge
