version: '3.7'
services:
  connect:
    image: debezium/connect
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: "broker:9092"
      GROUP_ID: "1"
      CONFIG_STORAGE_TOPIC: "qna.configs"
      OFFSET_STORAGE_TOPIC: "qna.offset"
      STATUS_STORAGE_TOPIC: "qna.status"
    networks:
      - poc_net
    
networks:
  poc_net:
    external: true
