version: '3.7'
services:
  broker:
    container_name: broker
    hostname: broker
    image: docker.redpanda.com/vectorized/redpanda:latest
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://broker:29092,OUTSIDE://broker:9092
      - --check=false
    ports:
      - 9092:9092
      - 29092:29092
    networks:
      - poc_net

networks:
  poc_net:
    external: true
