version: '3.7'
services:
  postgresql:
    image: debezium/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - poc_net

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@localhost.de"
      PGADMIN_DEFAULT_PASSWORD: "admin123"
    networks:
      - poc_net
      
  web_app:
    image: web_app
    depends_on:
      - postgresql
    ports:
      - "5000:5000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - poc_net

volumes:
  postgresql_data:
    driver: local
  pgadmin_data:
    driver: local
    
networks:
  poc_net:
    driver: bridge
    name: poc_net
